### ISSUE TITLE
URL rerouting for user connecting to another users notebook

### ISSUE THREAD

**Issue by kafonek** [jupyter/help#11]
I am using JupyterHub 0.5, running behind an Nginx reverse proxy in a subdirectory (https://myhost/jupyter/ redirects to the JupyterHub process running on localhost).  I am using a custom authenticator that gets authentication from Nginx-added headers.  For calls to my custom authenticator with a 'next' url argument, it also replaces the /user/_username _with the appropriate name (from Nginx headers) and redirects.

I have three users - 
joe (logged in)
bob (logged in)
jane (not logged in)

When I try to go to a notebook url with a user that is not logged in, the process redirects me to the login url with a 'next' argument, then the custom authenticator redirects me appropriate.  For instance if **joe** goes to https://myhost/jupyter/user/**jane**/notebooks/notebook_dir/example.ipynb, then I get the following redirects --

-- Auth credentials of user **Joe**
(REST method, url, response code)
GET https://myhost/jupyter/user/**jane**/notebooks/notebook_dir/example.ipynb - 302
GET https://myhost/jupyter/hub/user/**jane**/notebooks/notebook_dir/example.ipynb - 302
GET https://myhost/jupyter/hub/nginx_login?next=%2Fjupyter%2Fhub%2Fuser%2F**jane**%2Fnotebooks%2Fnotebook_dir%2Fexample.ipynb - 302
GET https://myhost/jupyter/hub/user/**joe**/notebooks/notebook_dir/example.ipynb - 302
GET https://myhost/jupyter/user/**joe**/notebooks/notebook_dir/example.ipynb - 304

I don't really know why I get those bounces around from /user/ to /hub/user and back, but in any case, the redirect works like I want it to.

When I try to go to a notebook url with a user that is logged in (but doesn't match my account), the process never ends up redirecting me to the login url.  This is what I get -

-- Auth credentials of user **Joe**
(REST method, url, response code)
GET https://myhost/jupyter/user/**bob**/notebooks/notebook_dir/example.ipynb - 302
GET https://myhost/jupyter/hub/?next=%2Fjupyter%2Fuser%2F**bob**%2Fnotebooks%2Fnotebook_dir%2Fexample.ipynb - 302
GET https://myhost/jupyter/user/**joe** - 302
GET https://myhost/jupyter/user/**joe**/tree/opt/jupyter/notebooks - 304

The last place that it drops me is interesting because that's the location that my custom authenticator sends a user to when there's no "next" url argument, but I don't see any redirects to /nginx_login in that series of 302's.  

I am hoping someone can help me understand the series of handlers, especially what handles the request to https://myhost/jupyter/hub, since I don't see /hub in the default handlers for base.py or pages.py.  Why is the behavior seeming to be different when I try to go to a /user/_username _of someone who is logged into the hub vs someone who is not?

Thanks so much in advance.

**Comment by minrk** [comment]
I *believe* this may be fixed in master, which changed some code related to redirects from single-user servers you don't own.

Here's the gist of what's going on:

1. Joe GETs Bob's notebook. Joe is not Bob, so Bob's server redirects to *it's* login URL, which is `/hub/` with `?next=` the original URL. This is because Bob doesn't know that Joe is Joe, only that Joe is not Bob. This is handled by the RootHandler in JupyterHub.
2. Joe's browser requests `/hub/?next=bob...`. Hub identifies that Joe is Joe, and redirects to Joe's server

After this point is where it's getting wonky. Where we most often get a redirect loop is when the Hub and Joe's server disagree about whether Joe is logged in - Hub sees login, redirects to Joe's server, Joe's server sees *not* logged in, redirects back, and on and on.

I've opened jupyter/jupyterhub#501 to force-set the user's cookie when the root handler is redirecting, which *may* catch this case.
