### ISSUE TITLE
Despite updating sklearn, jupyter notebook imports old version

### ISSUE THREAD

**Issue by jcclose1** [jupyter/help#125]
According to posts on StackOverflow and elsewhere, the problem is that I updated sklearn in the system terminal and not the terminal offered by the Jupyter interface. On my Mac it worked just fine to update in the Jupyter terminal. However, Windows does not support the terminal within Jupyter. So, how on earth do I get sklearn 0.18 imported to a notebook on a PC? Thanks!

**Comment by minrk** [comment]
It's important to make sure you use the same Python when installing or upgrading packages. You can check what's used in the notebook by looking at `sys.executable`. You can then upgrade sklearn with that Python in a console:

    C:\Path\To\Python.exe -m pip install --upgrade sklearn

**Comment by jcclose1** [comment]
Thanks for your reply!

**Comment by Carreau** [comment]
> Thanks for your reply!

Did it work ?

**Comment by jcclose1** [comment]
I wasn't able to figure it out using your suggestion. I tried it all in one line like you suggested, and alternatively by first navigating to python.exe and then entering the upgrade command on a different line. Got invalid syntax errors both times. However, I have this ipynb/terminal launcher for GraphLab machine learning library. It allowed me to open terminal in my "preferred python environment" and from there I successfully upgraded scikit-learn to v0.18. I am admittedly a CMD novice so whatever I was doing wrong to implement your suggestion was probably something simple and obvious. Thanks again!
![gl_launcher](https://cloud.githubusercontent.com/assets/21208154/22351318/1d83556c-e3cc-11e6-9fe4-0dd9260b5e59.PNG)

**Comment by Carreau** [comment]
> Got invalid syntax errors both times

Oh, that's atypical misundestanding. When you get these SyntaxError that's often because the command need to be ran from within a Shell, not Within Python itself. 

Upgrading/Installing things need to be done while outside Python.  It is rarely obvious to newcomers  which one has to be done when. Think of Python as "You can't change a piece of the engine while it is running". So you can't do the upgrade command from within Python itself. 

Usually you might get a hint (depending on the documentation). Commands that have to be done from within a Python shell start with `>>>` which indicate the python prompt. Commend that need to be run from the Shell/CMD often start with a `$` which is is typical prompt from a bash-shell on linux. 

Hope that make some sens and clarify things. 

Thanks, i'm closing as you have figured how to upgrade but feel free to keep asking questions and commenting.
