### ISSUE TITLE
Cannot POST to files, use PUT instead

### ISSUE THREAD

**Issue by AlecAivazis** [jupyter/help#15]
As I mentioned in #9, i'm working on a [RestfulContentManager](https://github.com/datascienceinc/RestfulContentManager/blob/master/restfulContentManager/restfulContentManager.py) (very much a WIP) that consumes an external API to retrieve files/directories. When I try to create a new file in the browser, I run into the following error message:

![screen shot 2016-04-06 at 2 30 56 pm](https://cloud.githubusercontent.com/assets/916317/14333568/340e5062-fc04-11e5-8b74-33614e82a969.png)

However, I'm not sure how/why the method used by the client has changed. The manager *does* POST when interacting with the API but I was under the impression that the `/files` mentioned in the error is on the jupyter server (which I don't think I changed), not the external api. Does someone by chance know what could have caused this? 

Sorry if there's not enough information to go off of, let me know if there's anything else you need.

**Comment by minrk** [comment]
POST creates a [new untitled file](https://github.com/ipython/ipython/wiki/IPEP-27:-Contents-Service#create-new-files) in a directory (Server decides the name of the new file). PUT [uploads a file](https://github.com/ipython/ipython/wiki/IPEP-27:-Contents-Service#upload-a-file) to a specific location (client specifies full path, not just directory).

So `POST /path/to/foo` means to create a new file in the **directory** `/path/to/foo`. If the ContentsManager sees that `/path/to/foo` exists and is a file, it gives you a message that if you really want to upload the *file* `/path/to/foo`, PUT is the right verb, because `POST /path/to/foo` means create a new file `/path/to/foo/Untitled##.ext`, which only makes sense if `foo` is a directory.

**Comment by AlecAivazis** [comment]
So is the problem that the`file_exists` check returned true when the server tried to handle the POST, indicating that something was wrong?

**Comment by minrk** [comment]
Yes, precisely. Double check that `file_exists` is returning False if a *directory* exists at the given path.

**Comment by AlecAivazis** [comment]
Perfect - now that I fixed that its working as expected. Thanks for the tip!
