### ISSUE TITLE
Cannot import numpy or pandas in Jupyter python3.6

### ISSUE THREAD

**Issue by camilogavo** [jupyter/help#162]
Hi,

I recently ask you guys because I had an issue with my Jupyter when I was running R.

Now I cannot import some libraries in Python

Any idea to solve it?

**Comment by takluyver** [comment]
It sounds like you're trying an import in two different installations of Python, or two different environments. Check `sys.executable` to see which Python and environment you're running in, and `sys.path` to see where it looks to import modules.

Python packages must be installed separately for each copy of Python you use, and if you are using virtualenvs or conda envs, packages must be installed into each environment where you need them. Either the package is not installed in one, or a different version of the package is installed.

To install packages to a particular Python installation or environment using pip, you can run it like this:

```shell
path/to/python -m pip install ...
# Replace path/to/python with the path of the Python executable (sys.executable)
```

If you are using conda environments, you can install packages from conda like this:

```shell
source activate myenv  # On Windows, just 'activate myenv' (no 'source')
conda install ...
```

[ This is a saved reply because I answer similar questions often - sorry if it doesn't exactly fit your case ]

**Comment by camilogavo** [comment]
thank you Tom. I have already managed this issue with your help.

**Comment by takluyver** [comment]
Great :-)

**Comment by OArmenta** [comment]
Hello guys. Seems I have the same problem. Install in  Canopy numpy and cant run it in jupyter. I have installed separately Anaconda in C:
Could you guide me to solve the issue.

**Comment by OArmenta** [comment]
My Canopy is pointing to  appdata/..../canopy
and my Jupyter is pointing to C:/Anaconda
I used: user_paths = os.environ['PYTHONPATH'].split(os.pathsep)
to find out
but dont know how to change to canopy my jupyter environment

**Comment by takluyver** [comment]
If you want to use Jupyter inside Canopy, install it with Canopy (and probably get rid of the Anaconda installation, to avoid confusion). Alternatively, install the packages you want to use in Anaconda. I don't recommend trying to share packages between them.
