### ISSUE TITLE
Jupyter Notebook is not giving any outputs.

### ISSUE THREAD

**Issue by Jamesvd02** [jupyter/help#190]

**Comment by minrk** [comment]
Can you provide some more detail? What OS, Browser? What version of the notebook (Help > About in the menu)? Are you running it locally on your laptop? What do you get from `jupyter troubleshoot`?

**Comment by Jamesvd02** [comment]
It's Windows 10, Microsoft Edge, Python 3.6.1, Anaconda 4.4.0, Jupyter 5.0, it's on my laptop, I don't know how to access jupyter troubleshoot

**Comment by minrk** [comment]
`jupyter troubleshoot` is a command you run in a terminal. You can access it by launching the `Anaconda Prompt` application and type `jupyter troubleshoot`.

Do you have Sophos or other antivirus and/or firewall software enabled? We have seen some such software on Windows interfere with network traffic. If you can temporarily disable it and see if the issue persists, at least we will know the cause. Sometimes the fix is to change the ip/port the notebook runs on. You can try:

    jupyter notebook --ip=localhost

or 

    jupyter notebook --ip=127.0.0.1

In these cases, often one or the other of those works and the other doesn't.

**Comment by sailesh97** [comment]
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)) - skipping

I am getting this error from jupyter troubleshoot.Same issue(not showing any output).Please help...

**Comment by admirer145** [comment]
Use below command
**_pip install ipython_** 
it worked for me
