### ISSUE TITLE
Best way to implement image viewing functionality in new kernel

### ISSUE THREAD

**Issue by Liberus** [jupyter/help#210]
Hi there! 
I'm currently playing with Cling(C++ interpreter) and it's jupyter kernel and I would want to display image inside Jupyter notebook using some kind of C++ function similar to IPython.display. 
What would be the best approach for that?

**Comment by Liberus** [comment]
I've asked the same question on SO, look like it's more responsive
[link](https://stackoverflow.com/questions/46123006/jupyter-how-to-implement-image-viewing-functionality-in-new-kernel)

**Comment by SylvainCorlay** [comment]
Hi @Liberus, I was actually going to reply to this, but I had accumulated quite a backlog.

Indeed, we are working on a pure C++ implementation of the Jupyter protocol in a library called [Xeus](github.com/QuantStack/xeus/). It can be used to create kernels in a native fashion (without relying on a python runtime).

Using xeus, we have created a new implementation of the cling kernel, [xeus-cling](https://github.com/QuantStack/xeus-cling) which is more featureful than the current python-based wrapper kernel. Among other things, it allows you to send custom messages to take advantage of

- the rich display system of jupyter
- jupyter widgets
- html help.

You can already try it [HERE](https://beta.mybinder.org/v2/gh/QuantStack/xtensor/master?filepath=notebooks/xtensor.ipynb), for the demo notebook of the xtensor library (think numpy for C++ and lazy computing).

1) Basic output / execution / exception handling + help:

![cpp-kernel](https://user-images.githubusercontent.com/2397974/30237916-9ab6c466-953c-11e7-8a5e-171a096ce4f4.png)

(The syntax for help is now a single heading question mark.) 

2) We do have some basic support for the widget protocol:

![peek 2017-08-16 12-45](https://user-images.githubusercontent.com/2397974/30237930-d92eb05a-953c-11e7-9585-6dced61c68de.gif)

The goal is to enable rich interactive widgets such as bqplot, ipyleaflet and ipyvolume eventually.

This is all under very active development, but if you are interested in joining forces. let us know. The more the merrier!

**Comment by SylvainCorlay** [comment]
Btw, there is a fairly active chat room on this here:

https://gitter.im/QuantStack/xeus

**Comment by Liberus** [comment]
Woah
That's some nice features you have there @SylvainCorlay! Nice. Never thought that there will be smth like that for C++.

Can you answer some more questions about xeus-cling:
What's the current state of the development? How is Windows build?
Any limitations on C++ code execution? Where can I get a list of features?
What're your goals and do you have some kind of roadmap?

**Comment by SylvainCorlay** [comment]
@Liberus we are very actively working on this.

 - The core `xeus` library is meant to be of a more general purpose than just the C++ kernel. We are using it to make SQL and Lua kernels as well. A backward incompatible change is coming up, that is the support binary messaging (which is a very cool hidden feature of the jupyter protocol used by data-intensive projects like ipyvolume). Once the binary messages come in, and we have a release, xeus should be fairly stable.

 - `xeus-cling` is another beast that is very much dependent on cling itself, and the main challenge is packaging. We are working on a standalone installer for the whole stack that will work on all platforms.

 - `xwidgets` is very early stage. The goal is to support all the core widgets and create backends for bqplot, ipyvolume and all. This is where most of the work is going now. (You may not see many commits in xwidgets, but we are working on separate packages that will be required). Note that xwidgets does not depend on xeus-cling, but only xeus, so it can be used by other kernels than the cling one, to give them widgets capabilities (such as rich display of sql outputs)

 - Limitations : you cannot re-define variables and classes, so you very much need to restart the kernel more often than in python.

 - The primary target is education. This will be used by a bunch of people for teaching C++ classes starting this September.

 - Projects like xplot (bqplot backend) and xvolume (ipyvolume backend) will depend on xtensor. (think "numpy for C++") here: http://xtensor.readthedocs.io/en/latest/numpy.html

 - The cling interpreter does not work so well on windows, especially on I/O operation. Thankfully, in the case of the notebook, we bypass this since I/O is redirected to the kernel messaging, so we can get around this. We have a manually built functional windows version, but have not packaged it properly yet.
