### ISSUE TITLE
Unable to run code

### ISSUE THREAD

**Issue by tanuj178** [jupyter/help#364]
Hi,

I am unable to run code in Jupyter. I have a hunch that it is not showing all items in the menu.

Please check.

Thanks
![screenshot](https://user-images.githubusercontent.com/38489578/40484895-a20ac31c-5f7a-11e8-8ba9-b23e131bbe29.jpg)

**Comment by takluyver** [comment]
Hi,

You've fallen into a common trap! Jupyter is built around notebooks, but it includes a very basic text editor so you can edit text files (like `.py` scripts) conveniently if you're accessing Jupyter on a remote server. You're in the text editor rather than the notebook editor.

To get a notebook, go back to the list of files, click the *New* menu, and select one of the kernel options under 'Notebooks'. If you've just installed Jupyter, there will probably only be one kernel option: Python 3.

That will create a .ipynb file and open it in the new interface.

**Comment by tanuj178** [comment]
Thanks so much for your response! I did some more research and figured this out while simultaneously read your comment. Thanks once again. Appreciate your support!
