### ISSUE TITLE
Kernel restarted without out of memory exception in docker

### ISSUE THREAD

**Issue by aisensiy** [jupyter/help#418]
My jupyter notebook is running in docker with a memory limitation. The problem is that the running kernel is restarted when it reach the memory limitation without any error report.

So is there some way to show the exception to tell user why the kernel is down?

**Comment by minrk** [comment]
That can be hard, because *any* memory allocation could fail. If you are lucky, it will be a Python call, and you could get a MemoryError. However, it's more likely that it will be a low-level call and the process will just die. Unfortunately, there is no good way to tell *why* the kernel was killed, but a tool like [nbresuse](https://github.com/yuvipanda/nbresuse) can give them a better monitor of their memory usage as it happens, which might help them figure it out.

**Comment by aisensiy** [comment]
Thanks for your reply. I will try to add some monitor to help user understand the reason why the kernel is shutdown.
