### ISSUE TITLE
syntax highlighting for other (non-python) languages

### ISSUE THREAD

**Issue by MatthewSteen** [jupyter/help#43]
Is there a way to enable syntax highlighting for non-Python languages in a notebook? I frequently use `%%Ruby` cell magic for work and this feature would be very helpful and happened automatically in a previous version of the notebook. Thanks for your help.

**Comment by willingc** [comment]
@MatthewSteen Syntax highlighting for non-Python languages is currently an open issue and a regression from expected behavior.

I'm going to merge this issue into https://github.com/jupyter/notebook/issues/1439 since it provides more information and helps us track the resolution in one place. I'm sorry, but I'm hopeful for a timely resolution. Thanks!

**Comment by MatthewSteen** [comment]
**Update:** using `%%script ruby` instead of the `%%ruby` shortcut enables syntax highlighting.

**Comment by willingc** [comment]
@MatthewSteen Hmm... Are you using the latest version https://github.com/SciRuby/iruby v0.2.9? How did you track down this resolution? I'm glad you have it working.

**Comment by Carreau** [comment]
%%script ruby has nothing to do with iruby. Are you sure it works, or does
it just apply Python highlighting to Ruby code.

**Comment by MatthewSteen** [comment]
@Carreau upon further inspection it appears to just apply Python highlighting. e.g. if using `dir` as a variable name it will be green.
