### ISSUE TITLE
Reading HTML Files

### ISSUE THREAD

**Issue by diggetybo** [jupyter/help#49]
Hello

First let me say I have been using Jupyter for use with Python and occasionally JS, and love it so far. 

I'm using google chrome for my browser. I have two related issues:

2.  When I try to open up a HTML file via Jupyter's local host (and using the Jupyter GUI), it doesn't open it in HTML format, it just shows me the raw HTML code. Is there someway to tell Jupyter I only want the HTML view?

I read Jupyter has certain 'trust' measures. As far as I know though, there seems to be know way to 'trust' a html file so that it loads. Again I'm not sure if that's the underlying issue.

Obviously, viewing the raw code is helpful, but sometimes I would like to leverage having a local host like Jupyter's at my disposal for testing out how a webpage will look and function. Is it possible to do such a thing?

Second issue is as follows:

2. Whenever I run Jupyter and think I have a local host going (which I know I do to some extent because I can run certain python libraries that require HTTP protocol within Jupyter), however when I click on an html file (in Jupyter's local host home directory, but not using Jupyter's GUI, in otherwords just opening the containing folder and hitting the enter key on it) it doesn't load properly in the browser. In the address bar it just shows the real path like "C:\Users\Me\file.html" the html doesn't seem to know it can use my local host. As a result, the http protocol is not brought to bear and certain errors occur like when I try to read data from a csv or json when I check developer's tools.

So, I'm not sure if Jupyter is creating a local host for only notebook files and not html files? or did I not point something the right way?

**Comment by minrk** [comment]
First question:

There isn't a link to the HTML view. You can enter the URL manually by replacing 'edit' in the URL with 'files'. You can also get to the HTML view with a link from a notebook, e.g. in a markdown cell:

    [link text](./file.html)

Trust only applies to notebooks, because they are the only files which have the ability to execute code on open (part of why there is only an edit link, and not a view link for html files, which would allow execution on your system).

Second question:

Your system doesn't know that the notebook web application is able to open or view files, HTML or otherwise. The system does, however, know that it can open HTML files with a browser by pointing to a file URL. If you want to open files in the jupyter environment, you should use the Jupyter UI to do that.

**Comment by diggetybo** [comment]
Hey minrk,

Thanks a ton for your suggestions. I have been tinkering away at it pitifully for days. Question one is laid to rest. I can now view html by replacing edit with files. Never knew it was so easy. Thanks again.

Question 2 I'm still not so sure on. Do you mean I can only use the local host for viewing webpages on my computer using Jupyter's UI? I was hoping to interface Jupyter with some other applications that benefit from a local host.

For example, I have an PPT plugin that lets me insert a live webpage into my presentation. When online, its cool, but if I try some local host urls, they never load, despite having Jupyter running in the background. I found that odd, because when I copy and paste the local host url (with 'files' for html viewing) it works fine.

So, what it boils down to, is can Jupyter help me out in this regard? Or is it better to find a different local host? I know Python has a local host, is that any different?

**Comment by takluyver** [comment]
On 3 June 2016 at 17:13, diggetybo <notifications@github.com> wrote:

> Do you mean I can only use the local host for viewing webpages on my
> computer using Jupyter's UI? I was hoping to interface Jupyter with some
> other applications that benefit from a local host.
>
You don't need to use the UI - as I think you've found, you can construct a
URL to any file that's available to Jupyter and open it directly in the
browser. But clicking on it in your file manager won't do this, because the
file manager doesn't know about Jupyter.

> For example, I have an PPT plugin that lets me insert a live webpage into
> my presentation. When online, its cool, but if I try some local host urls,
> they never load, despite having Jupyter running in the background. I found
> that odd, because when I copy and paste the local host url (with 'files'
> for html viewing) it works fine.
>
That's odd. I don't have powerpoint to try, but maybe it's specifically
blocking localhost URLs for some reason. Does it work if you use 127.0.0.1
instead of localhost?

**Comment by diggetybo** [comment]
Hey thanks for the additional advice,

I tried out the 127.0.0.1 at the start of the URL, it worked like normal in the browser, but in the PPT it didn't load. Let me do some more trouble shooting with this particular plug-in to rule out anything that isn't directly related to Jupyter.

I will post my findings either way when I can.

Thanks again for the quick help, Jupyter has such an awesome community!

**Comment by Carreau** [comment]
I'm going to assume this has been solved. Thanks!
