### ISSUE TITLE
Passing a list through command line

### ISSUE THREAD

**Issue by akhmerov** [jupyter/help#92]
I'm trying to execute  
`jupyter nbconvert --to html --Exporter.preprocessors=["my.custom.Preprocessor"] notebook.ipynb`  
but it generates the following error:
`traitlets.traitlets.TraitError: The 'preprocessors' trait of a HTMLExporter instance must be a list, but a value of class 'str' (i.e. '[my.custom.Preprocessor]') was specified.`

Obviously I could also dump this line into a config file, but cli seems superior to a one-liner config file. Hence the questions:
1. Is something like this supposed to work? If no, then `jupyter nbconvert --help-all` should probably only list the non-list options.
2. If it is supposed to work, what's the correct way?

**Comment by takluyver** [comment]
It is supposed to work, but getting the quoting and escaping right so that the characters you want make it to Jupyter's command line parsing is tricky. The shell is trying to be smart with it before it launches the subprocess.

**Comment by akhmerov** [comment]
Hmm, `\["my.custom.Preprocessor"\]` doesn't work either...

**Comment by takluyver** [comment]
I suspect it's the quotes you need to escape.

**Comment by akhmerov** [comment]
You're right, `jupyter nbconvert --to html --Exporter.preprocessors=[\"my.custom.Preprocessor\"] notebook.ipynb` is the correct syntax.

**Comment by minrk** [comment]
By the way, traitlets 5.0 will use argparse's container arguments to give a more sensible way to specify these on the command-line, and the old list-literal will stop working.

https://github.com/ipython/traitlets/pull/322

**Comment by takluyver** [comment]
Hang on, we're going to break command line syntax that currently works when a dependency gets upgraded? That seems... unfortunate.

**Comment by minrk** [comment]
@takluyver that's why I was soliciting feedback at various meetings, etc. on that PR, but all I got was comments that people had given up trying to use the existing (undocumented?) container-traits syntax as they were because it was such a mess. I'll make sure to put in some time to see if I can get a deprecated backward-compatible version in as well, so it's not broken unnecessarily.

My position about traitlets 4.x and before is that while you sort-of can specify list traits on the CLI, it's not really supported, and such traits can only be specified in a reasonable manner in config files.

**Comment by minrk** [comment]
@takluyver I opened ipython/traitlets#338 and ipython/traitlets#339, both of which keep the old-style working with a deprecation message, depending on which way we go. I think it will be nice to be able to actually recommend list args on the command-line, which we haven't been able to do before.

**Comment by ankostis** [comment]
> Hang on, we're going to break command line syntax that currently works when a dependency gets upgraded? That seems... unfortunate.

But was it really officially supported the old <4.x behavior for container-traits by Jupyter?
Were there any examples given in the document, suggesting to pass lists like that?
Or is there a MUST_USE flag people have been faily using the old syntax?

I mean, it's worth the effort to dig further a bit into this question, 
instead of polluting the traitlets's code base with convoluted compatibility code for an accidental "feature " of the past.

**Comment by minrk** [comment]
> But was it really officially supported the old <4.x behavior for container-traits by Jupyter?

Yes.

> Were there any examples given in the documents, suggesting to pass lists like that?

Perhaps not in documentation, but in support requests, like this one.

> I mean, it's worth the effort to dig further into this question,
instead of polluting the traitlets's code base with convoluted compatibility code for an accidental "feature " of the past.

It wasn't an accident, it was a feature, just one that turned out to be unpleasant to use.

**Comment by DavidPowell** [comment]
I am trying to configure the `PDFExporter.latex_command` from the command line which requires a list. My reason for doing this is that xelatex seems to choke on my generated .tex file, but pdflatex apparently has no problem. 

When specifying this command option, I am running into the same issue mentioned here. I see that the linked issues offer some kind of solution, but I am still unclear as to the correct syntax to use.
